#!/bin/sh

twistd -ny demo-webserver.tac &
twistpid="$!"
trap "kill $twistpid" TERM INT
python demo-db.py $@

# python demo-db.py &
# serverpid="$$"
# trap "kill $serverpid" TERM
# twistd -ny demo-webserver.tac
# cd ..